# Configuration options for dev
tornado:
  port: 8888
  debug: true # will reload server on each change to python files
  xsrf: false # for now until we get to it

postgres:
  hostname: localhost
  database: postgres_cdc_dev
  user: postgres
  db_url: postgres://{user}:{password}@{hostname}/{database}

app-env: dev

asset:
  allowed_asset_types:
    - background
    - object
  # This will be the S3 bucket URL in prod
  prefix_url: http://localhost:8888/static/

script:
  table-order:
    - asset
    - scenario
    - scene
    - object
    - statistics

cache:
  # seconds in day: 24 * 60 * 60
  expire_time: 86400
  # how frequently to update cache (in seconds), 60 seconds for dev, for now
  update_time: 5
  # no need to update cache for dev, except for testing purpose
  periodic_callback_enabled: false
