# Configuration options for dev
tornado:
  port: 8888
  debug: true # will reload server on each change to python files
  xsrf: false # for now until we get to it

postgres:
  hostname: localhost
  database: postgres_cdc_dev
  user: postgres
  db_url: postgres://{user}:{password}@{hostname}/{database}

app-env: dev

asset:
  allowed_asset_types:
    - background
    - object

script:
  table-order:
    - asset
    - scenario
    - scene
    - object
    - statistics

cache:
  # seconds in day: 24 * 60 * 60
  expire_time: 86400
